### ISSUE TITLE
Abandoned ?

### ISSUE THREAD

**Issue by quasar098** [mehaase/encoding-tools#31]
I was wondering if this project has been abandoned because it is very interesting and has potential but I have seen that there have not been any commits on this.

this seems very similar to cyberchef or my text format wizard, but a graphical version, which intrigues me.

**Comment by mehaase** [comment]
It’s not totally abandoned. I haven’t had time to work on it a while but if people comment on issues or submit PRs I would eventually make time for them.

**Comment by quasar098** [comment]
Ok
